name: dev - API 서버 배포

on:
  workflow_dispatch:
  workflow_run:
    branches:
      - develop
    workflows:
      - django 테스트
    types:
      - completed

env:
  APP_ENV: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RUN (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo ${{ github.head_ref }}
      - name: RUN (workflow_run)
        if: github.event_name == 'workflow_run'
        run: |
          echo ${{ github.event.workflow_run.head_branch }}
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: .github/version.yaml
      - name: RUN
        run: |
          git status
