name: dev - API 서버 배포

on:
  workflow_dispatch:
  workflow_run:
    branches:
      - develop
    workflows:
      - django 테스트
    types:
      - completed

env:
  APP_ENV: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 브랜치 확인
        id: map-branch
        run: |
          if [[ ${{github.event_name}} == 'workflow_run' ]]; then
              echo "::set-output name=branch::${{ github.event.workflow_run.head_branch }}"
          else
              echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          fi
      - name: check
        run: |
          echo ${GITHUB_REF#refs/heads/}
          echo !!!

          echo ${{ steps.map-branch.outputs.branch }}
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: .github/version.yaml
      - name: RUN
        run: |
          git status
