name: 서버 배포 알림

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: 파이썬 3.10 셋업
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 모듈 설치
        run: |
          pip install requests
      - name: 서버 배포 알림
        run: |
            python .github/workflows/notify_pr.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATLASSIAN_DOMAIN: nrise
          ATLASSIAN_USER: ${{ secrets.ATLASSIAN_USER }}
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
